[package]
name = "zed_golangci_lint"
version = "0.2.0"
edition = "2021"
publish = false
license = "MIT"

[lib]
path = "src/golangci-lint.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.2.0"
