id = "golangci-lint"
name = "golangci-lint"
description = "golangci-lint support."
version = "0.2.0"
schema_version = 1
authors = ["Jordan Gregory <jordan@j4ng5y.dev>", "Joakim Engeset <joakim.engeset@gmail.com>"]
repository = "https://github.com/zed-extensions/golangci-lint"

[language_servers.golangci-lint]
name = "golangci-lint"
languages = ["Go"]
